# Generated by Django 3.1.6 on 2021-05-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipowebsite', '0003_currentipo_upcomming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentipo',
            name='pricel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currentipo',
            name='priceu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currentipo',
            name='quantitymin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
