# Generated by Django 3.1.6 on 2021-05-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipowebsite', '0004_auto_20210501_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentipo',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
