# Generated by Django 3.1.6 on 2021-05-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipowebsite', '0007_careerinfo_stockcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerinfo',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
