# Generated by Django 3.1.6 on 2021-05-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipowebsite', '0008_careerinfo_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('qtype', models.CharField(max_length=75)),
                ('qtext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ipoforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compname', models.CharField(max_length=75)),
                ('investatus', models.CharField(max_length=75)),
                ('quanofshare', models.IntegerField()),
                ('pricpershare', models.IntegerField()),
                ('pan', models.CharField(max_length=10)),
                ('applicantname', models.CharField(max_length=75)),
                ('date', models.DateField()),
                ('depository', models.CharField(default='CDSL', max_length=75)),
                ('dpid', models.CharField(max_length=16)),
                ('dpname', models.CharField(max_length=50)),
                ('bankname', models.CharField(max_length=50)),
                ('accountnum', models.IntegerField()),
                ('nationality', models.CharField(max_length=75)),
            ],
        ),
    ]
