# Generated by Django 3.1.6 on 2021-05-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipowebsite', '0009_contactus_ipoforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipoforms',
            name='accountnum',
            field=models.CharField(max_length=16),
        ),
    ]
